package com.example.models

import kotlinx.serialization.Serializable
import java.math.BigDecimal

// we are using Serializable here because we want to conver the underlying data
// to and from JSON format
// this is a data class. We are implementing data class because, we want to
// utilize automatically generated function by kotlin for data classes. Like
// toString, equals, hashCode, copy, etc.
@Serializable
data class Transaction(
    val transactionId: Int? = null, // nullable because it is generated by database
    val userId: Int,
    val title: String,
    val category: String,
    val subCategory: String?, // optional
    val transactionType: String,
    val amount: String, // using string to handle decimal values will convert later
    val date: String, // using string to handle date will convert later
    val description: String?, // optional
    val location: String?,
    val createdAt: String? = null // nullable and generated by database
)